//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountersLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterOptions
    {
        public int CounterID { get; set; }
        public string CounterType { get; set; }
        public string CounterDescription { get; set; }
    }
}
