//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountersLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterValue
    {
        public int CounterValudId { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> CounterID { get; set; }
        public Nullable<int> CounterValue1 { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> DateOfEnterValue { get; set; }
    }
}
